services:
  # Base de datos con volumen nombrado para persistencia (IE3)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: innovatech_db
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data:/var/lib/postgresql/data # Requerimiento de persistencia (cite: 33, 98)
    networks:
      - back-net

  # Microservicio Ventas
  back-ventas:
    build: ./back-Ventas_SpringBoot
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/innovatech_db
    networks:
      - back-net

  # Microservicio Despachos
  back-despachos:
    build: ./back-Despachos_SpringBoot
    depends_on:
      - db
    networks:
      - back-net

  # Frontend expuesto (IE5)
  frontend:
    build: ./front_despacho
    ports:
      - "80:80" # Accesible vía IP pública (cite: 56, 121)
    networks:
      - back-net

# Definición de volumen nombrado (Justificación: mayor control que bind mounts) (cite: 35, 99)
volumes:
  db_data:

networks:
  back-net: