services:
  db:
    image: mysql:8.0
    container_name: innovatech_db
    restart: always
    environment:
      - MYSQL_DATABASE=innovatech_db
      - MYSQL_ROOT_PASSWORD=password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back-net

  back-ventas:
    image: rexdeadx/innovatech-ventas:latest
    container_name: back-ventas
    restart: always
    depends_on:
      - db
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=password123
    ports:
      - "8080:8080"
    networks:
      - back-net

  back-despachos:
    image: rexdeadx/innovatech-despachos:latest
    container_name: back-despachos
    restart: always
    depends_on:
      - db
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=password123
    ports:
      - "8081:8081"
    networks:
      - back-net

  frontend:
    image: rexdeadx/innovatech-front:latest
    container_name: frontend-innovatech
    restart: always
    ports:
      - "80:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - back-net

volumes:
  db_data:

networks:
  back-net: